name: Generate and Publish Doxygen Documentation

# Trigger the workflow on every push to the main branch
on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, canceling runs in progress
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Build HTML documentation
        # Runs Doxygen using the config file located in the doc/ folder
        run: doxygen docs/Doxyfile

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload HTML artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This path MUST match the OUTPUT_DIRECTORY defined in your Doxyfile
          path: 'docs/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4